# -*- coding: utf-8 -*-
from selenium.webdriver.common.by import By


class MainPageLocators:
    ACTUAL_CITY = (By.XPATH, "//span[@class='b-geo--opener']")
    BUTTON_YES = (By.CSS_SELECTOR, "div>div>ul>li:nth-child(1)>a")
    ICON_LK = (By.XPATH, "//*[@id='personal-account-button']")
    BUTTON_LOG_IN = (By.XPATH, "//*[@class='Header_Dropdown__Inner']/div[2]/div[2]")
    ENTRANCE_FIELD_EMAIL = (By.XPATH, "//*[@class='Tabs__Card']/div[1]/form/div[1]/div/input")
    ENTRANCE_FIELD_PASSWORD = (By.XPATH, "//*[@id='Пароль']")
    BUTTON_ENTER = (By.XPATH, "//button[text()='Вход']")
    ACTUAL_NAME_DROPDOWN_LOGGED = (By.XPATH, "//div[@class='Header_DropdownLogged__HeadItem']")
    ERROR_EMAIL_FIELD = (By.XPATH, "//div[text()='Введите электронную почту']")
    ERROR_PASSWORD_FIELD = (By.XPATH, "//div[text()='Введите пароль']")
    ERROR_USER_NOT_FOUND = (By.XPATH, "//div[text()='User not found.']")
    ERROR_SET_ACTUAL_EMAIL = (By.XPATH, "//div[text()='Введите настоящий адрес электроной почты']")
    ERROR_INVALID_USER_OR_PASSWORD = (By.XPATH, "//div[text()='Invalid username or password.']")
    HEADER_DROPDOWN_LOGGED_PROFILE = (By.XPATH, "//a[text()='Профиль']")


class LkProfilePageLocators:
    CHECK_EMAIL = (By.XPATH, "//div[@class ='Input__FixedText']")
    FIELD_NAME = (By.XPATH, "//input[@name='first_name']")
    FIELD_LAST_NAME = (By.XPATH, "//input[@name='last_name']")
    FIELD_MIDDLE_NAME = (By.XPATH, "//input[@name='middle_name']")
    FIELD_DATE_OF_BIRTH = (By.XPATH, "//input[@name='date_of_birth']")
    FIELD_PHONE = (By.XPATH, "//input[@name='phone']")
    BUTTON_SAVE = (By.XPATH, "//button[@class='Button__Wrapper Button__BgOrange Button__SizeLg Button__LengthXs']")
    PROFILE_DROPDOWN = (By.XPATH, "//div[@class='ProfileDropdown_DropdownButton__Button']")
    ACTUAL_NAME_PROFILE_DROPDOWN = (By.XPATH, "//b[@class='ProfileDropdown_DropdownLogged__Name']")
    ERROR_EMPTY_NAME = (By.CSS_SELECTOR, "form>div:nth-child(2)>div.Input__ErrorMessage")
    ERROR_EMPTY_LAST_NAME = (By.CSS_SELECTOR, "form>div:nth-child(3)>div.Input__ErrorMessage")
    ERROR_BIRTH = (By.CSS_SELECTOR, "form>div:nth-child(5)>div:nth-child(1)>div.Input__ErrorMessage")
    ERROR_PHONE = (By.CSS_SELECTOR, "form>div:nth-child(5)>div:nth-child(2)>div.Input__ErrorMessage")
    ERROR_LONG_NAME = (By.CSS_SELECTOR, "form>div:nth-child(2)>div.Input__ErrorMessage")
    ERROR_LONG_LAST_NAME = (By.CSS_SELECTOR, "form>div:nth-child(3)>div.Input__ErrorMessage")
    ERROR_LONG_MIDDLE_NAME = (By.CSS_SELECTOR, "form>div:nth-child(4)>div.Input__ErrorMessage")
    ERROR_SAVE = (By.XPATH, "//div[@class='Button__Error']")


class RegistrationPageLocators:
    LOGO_ROBOMARKET = (By.XPATH, "//div/div/a[@class='b-logo--link']")
    MAIL_PATH1 = (By.XPATH, "//form/input[1][@type='text']")
    MAIL_PATH2 = (By.XPATH, "//select[@id='domain']")
    CHECK_MAIL = (By.CSS_SELECTOR, "#emailarea>form>button")
    ICON_LK = (By.XPATH, "//*[@id='personal-account-button']")
    BUTTON_REGISTRATION = (By.XPATH, "//div[4]/ul/li[2]/div[2]/div/div[3]/div[2]")
    BUTTON_GO_TO_REG = (By.XPATH, "//button[text()='Зарегистрироваться']")
    BUTTON_PASSWORD = (By.XPATH, "//div[4]/div/div/div[2]/form/div[3]/button")
    BUTTON_DISABLED_CONFIRM_RECOVERY = (By.XPATH, "//div[2]/form/div[3]/button")
    BUTTON_LOGOUT_LK = (By.XPATH, "//span[text()='Выход']")
    BUTTON_FORGET_PASSWORD = (By.XPATH, "//span[@class='Link__LinkedText']")
    BUTTON_CONFIRM_RECOVERY_PASSWORD = (By.XPATH, "//button[@class='Button__Wrapper b-button b-button---orange']")
    BUTTON_CONFIRM_PASSWORD_DISABLED = (By.XPATH, "//button[text()='Подтвердить']")
    BUTTON_RECOVERY_GO_TO_CATALOG = (By.XPATH, "//a[text()='Перейти в каталог']")
    REG_FIELD_EMAIL = (By.XPATH, "//div[2]/form/div[1]/div/input")
    REG_FIELD_FIRST_NAME = (By.XPATH, "//div[2]/div[2]/form/div[2]/div/input")
    REG_FIELD_LAST_NAME = (By.XPATH, "//div[2]/div[2]/form/div[3]/div/input")
    RECOVERY_PASSWORD_FIELD_EMAIL = (By.XPATH, "//*[@id='Электронная почта']")
    POPUP_REG = (By.XPATH, "//div/div[1][text()='Регистрация']")
    POPUP_PASSWORD_RECOVERY = (By.XPATH, "//div[text()='Восстановление пароля']")
    POPUP_PASSWORD_RECOVERY_SEND = (By.XPATH, "//div[3]/div/div/div[2]/div/div/button")
    POPUP_PASSWORD_RECOVERY_SEND_AGAIN = (By.XPATH, "//button[text()='Отправить повторно']")
    POPUP_PASS_REC_SUCCESS = (By.XPATH, "//*[@class='src_pages_ResetPassword_RestorePasswordSuccessLetter__Text']")
    SWITCH_TO_IFRAME_LETTER_LINK = (By.XPATH, "//iframe[@id='messageiframe']")
    SECMAIL_MESSAGE_DETAILS = (By.XPATH, "//div[@class='messagedetails1']")
    SECMAIL_GO_BACK = (By.XPATH, "//span[@class='goback']")
    SECMAIL_REFRESH = (By.XPATH, "//a[@id='refreshMailBtn']")
    LETTER_GO_TO_LINK = (By.XPATH, "//*[text()='по этой ссылке']")
    LETTER_LINK_CREATE_PASSWORD = (By.XPATH, "//tbody/tr[3]/td/a")
    INPUT_PASSWORD1 = (By.XPATH, "//div[4]/div/div/div[2]/form/div[1]/div/input")
    INPUT_PASSWORD2 = (By.XPATH, "//div[4]/div/div/div[2]/form/div[2]/div/input")
    INPUT_NEW_PASSWORD1 = (By.XPATH, "//input[@id='Укажите новый пароль']")
    INPUT_NEW_PASSWORD2 = (By.XPATH, "//input[@id='Повторите новый пароль']")
    DROPDOWN_LOGIN = (By.XPATH, "//div[@class='Header_DropdownLogged__HeadItem']")
    LETTER_CHECK = (By.XPATH, "//tbody/tr[2]/td[@align='center']")
    LETTER_CONFIRM_EMAIL = (By.XPATH, "//*[text()='Подтвердите свою электронную почту']")
    LETTER_REGISTRATION_DONE = (By.XPATH, "//*[text()='Регистрация завершена']")
    LETTER_REGISTRATION_SUCCESS = (By.XPATH, "//tr[2]/td/table/tbody/tr[2]/td")
    LETTER_RECOVERY_PASSWORD = (By.XPATH, "//*[text()='Восстановление пароля']")
    ERROR_EMPTY_EMAIL = (By.XPATH, "//div[text()='Введите электронную почту']")
    ERROR_EMPTY_FIRST_NAME = (By.XPATH, "//div[text()='Введите имя']")
    ERROR_EMPTY_LAST_NAME = (By.XPATH, "//div[text()='Введите фамилию']")
    ERROR_SET_ACTUAL_EMAIL = (By.XPATH, "//div[text()='Введите настоящий адрес электроной почты']")
    ERROR_NOT_WELL_FORMED_EMAIL = (By.XPATH, "//div[text()='Not a well-formed email address.']")
    ERROR_EMAIL_ALREADY_EXIST = (By.XPATH, "//div[2]/div[2]/div/div[@class='ErrorMessage__ErrorMessage']")
    ERROR_EMAIL_NOT_FOUND = (By.XPATH, "//div[@class='ErrorMessage__ErrorMessage']")
    ERROR_EMPTY_PASSWORD1 = (By.XPATH, "//div[text()='Введите пароль']")
    ERROR_EMPTY_PASSWORD2 = (By.XPATH, "//div[text()='Введите пароль еще раз']")
    ERROR_TOO_SHORT_PASSWORD1 = (By.XPATH, "//div[1]/div[text()='Слишком короткий пароль']")
    ERROR_TOO_SHORT_PASSWORD2 = (By.XPATH, "//div[2]/div[text()='Слишком короткий пароль']")
    ERROR_PASSWORD_WITHOUT_LETTER1 = (By.XPATH, "//form/div[1]/div[2]")
    ERROR_PASSWORD_WITHOUT_LETTER2 = (By.XPATH, "//form/div[2]/div[2]")
    ERROR_DIFFERENT_PASSWORD = (By.XPATH, "//div[text()='Пароли должны совпадать']")
    ERROR_RECOVERY_PASSWORD_EMPTY_MAIL = (By.XPATH, "//div[text()='Заполните поле']")


class LkmPageLocators:
    LKM_AUTH_FIELD_LOGIN = (By.XPATH, "//div[2]/form/div/div[1]/input")
    LKM_AUTH_FIELD_PASSWORD = (By.XPATH, "//div[2]/form/div/div[2]/input")
    LKM_AUTH_CHECKBOX_REMEMBER = (By.XPATH, "//*[@id='root']/div/div[2]/div/div/div[2]/form/div/label")
    LKM_AUTH_BUTTON_LOG_IN = (By.XPATH, "//div[2]/form/div/button")
    LKM_BUTTON_LOG_OUT = (By.XPATH, "//div[1]/div[1]/div/button[2]")
    LKM_CURRENT_EMAIL_MERCHANT1_PROFILE_DROPDOWN = (By.XPATH, "//*[@id='root']/div/div[1]/div[1]/button")
    TABLABEL_MODULE_AUTHORIZATION = (By.XPATH, "//div[2]/div/div/div[2]/div/div[1]/div[1]")
    LKM_AUTH_ERROR = (By.XPATH, "//*[@id='root']/div/div[2]/div/div/div[2]/form/div/span")
